spring.application.name=MiniKintsugi

spring.datasource.url=jdbc:postgresql://localhost:5432/minikintsugi

spring.datasource.username=postgres

spring.datasource.password=Naughtystone999*


spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
